services:
  fastapi:
    volumes:
      - ./:/app
    command: >
      poetry run uvicorn app:app --host 0.0.0.0 --port 8000 --reload
  init-db:
    # Disable the one-shot job during iterative dev
    command: ["true"]
